### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by mcl12345** [paulogr/dstatuspage#3]
$ dstatuspage --daemon 
/home/sb/.nvm/versions/node/v5.12.0/lib/node_modules/dstatuspage/bin.js:5
let exec = help
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:148:18)
    at node.js:405:3

**Comment by paulogr** [comment]
Hi @mcl12345 thanks for reporting!

Are you using node 5.X? 

Just supposed to work for node version +8.
