### ISSUE TITLE
Program exits when it tries to start node

### ISSUE THREAD

**Issue by hayzey** [paulogr/dstatuspage#4]
I'm getting the following error when running `dstatuspage --daemon`...

```
Initializing IPFS...
/usr/local/lib/node_modules/dstatuspage/ipfs.js:79
        this.node.start((err, ipfsapi) => {
                  ^

TypeError: Cannot read property 'start' of undefined
    at startNode (/usr/local/lib/node_modules/dstatuspage/ipfs.js:79:19)
    at node.init (/usr/local/lib/node_modules/dstatuspage/ipfs.js:95:13)
    at Object.run (/usr/local/lib/node_modules/dstatuspage/node_modules/ipfsd-ctl/src/daemon-node.js:132:16)
    at Object.f [as error] (/usr/local/lib/node_modules/dstatuspage/node_modules/once/once.js:25:25)
    at Stream.listeners.done.once (/usr/local/lib/node_modules/dstatuspage/node_modules/ipfsd-ctl/src/exec.js:38:25)
    at Stream.f (/usr/local/lib/node_modules/dstatuspage/node_modules/once/once.js:25:25)
    at emitTwo (events.js:126:13)
    at Stream.emit (events.js:214:7)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
```

I'm running it under Node v8.9.4

**Comment by paulogr** [comment]
Still having this?

Just launch a docker with debian and install the package globally using `npm i -g dstatuspage` and can't reproduce your problem.

If you have any further information to give...

Thanks for reporting.

**Comment by hayzey** [comment]
I can't replicate the issue now 🤔

**Comment by 100Errors** [comment]
Had the same issue. I just needed to run it as root: `sudo dstatuspage --daemon`

**Comment by paulogr** [comment]
This is not supposed to be used as root.... did you install it using sudo?

**Comment by 100Errors** [comment]
Yes, it had issues with file permissions and I did not want to set the file permissions, so I installed it using sudo

**Comment by paulogr** [comment]
Npm website has very clear instructions about how to handle this
https://docs.npmjs.com/getting-started/fixing-npm-permissions
